[package]
name = "kdl"
version = "2.0.0"
description = "Official Rust KDL parser"
authors = ["Kat Marchán <kzm@zkat.tech>", "KDL Community"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://kdl.dev"
repository = "https://github.com/kdl-org/kdl-rs"
keywords = ["kdl", "document", "serialization", "config"]
edition = "2018"

[dependencies]
nom = { version = "6.0.1", default-features = false }
phf = { version = "0.8.0", features = ["macros"] }
thiserror = "1.0.22"
