[package]
name = "kdl"
version = "0.0.0"
description = "KDL Document Language"
authors = ["Kat Marchán <kzm@zkat.tech>", "KDL Community"]
license-file = "LICENSE.md"
readme = "README.md"
homepage = "https://kdl.dev"
repository = "https://github.com/kdl-org/kdl-rs"
keywords = ["kdl", "document", "serialization", "config"]
edition = "2018"

[dependencies]
nom = "6.0.1"
thiserror = "1.0.22"
